### ISSUE TITLE
Use Consumer Groups to process stream messages

### ISSUE THREAD

**Issue by Ishatt** [near/queryapi#202]
By default, Redis Streams ‘fanout’ messages to all consumers. This is undesirable as we want a single message to be processed once.

[Consumer Groups](https://redis.io/docs/data-types/streams/#consumer-groups) provide a way to ‘load balance’ messages across multiple consumers. This will allow us to ‘parallelise’ historical processing, i.e. we can scale out to X processes to handle the backfill. For real-time, we’ll most likely want to stick with a single consumer, to ensure the stream is processed sequentially.

Consumer Groups also provide ‘message acknowledging’ to signify which messages have/have not been processed. This can replace the Key which is being used to store the ‘last processed block’.

Consumers are ‘assigned’ messages, which makes them invisible to other consumers. If the process dies and never recovers, those messages will not automatically be sent to another consumer. This ‘claiming’ process needs to be handled manually, and might require another service to monitor it.

**Comment by pkudinov** [comment]
@morgsmccauley is this still relevant? We now have a separate stream per indexer, so we don't really need to create consumer groups, right?
