### ISSUE TITLE
Optimize Runner Streamer Message Acquisition

### ISSUE THREAD

**Issue by Ishatt** [near/queryapi#204]
Description

Currently the Indexer Runner fetches and constructs the Streamer Message from S3. Instead, we can store real-time messages in Redis to avoid the; amount of duplicate requests, and the latency cost. The message can have a short TTL to avoid consuming too much memory, and we can fallback on fetching the message if it doesn’t exist. Processing of the streamer message such as the call to renameUnderscoreFieldsToCamelCase should be done before caching to further reduce latency. 

Publish cache hits/misses to Prometheus so we can fine tune TTL.

Upgrade AWS SDK from v2, which is to be deprecated.

Pre-Fetch Historical Blocks from S3 during historical processing. 
```[tasklist]
### Tasks
- [ ] https://github.com/near/queryapi/issues/262
- [ ] https://github.com/near/queryapi/issues/264
```

**Comment by darunrs** [comment]
PR: https://github.com/near/queryapi/pull/241
