### ISSUE TITLE
Batch commands with Pipelines

### ISSUE THREAD

**Issue by Ishatt** [near/queryapi#206]
Description

To increase throughput, and avoid network costs, we can use [Redis pipelining](https://redis.io/docs/manual/pipelining/) to batch commands sent to Redis.

**Comment by pkudinov** [comment]
@morgsmccauley could you please provide more context here if this ticket is still needed. If not, simply close it

**Comment by morgsmccauley** [comment]
@pkudinov I don't think this is needed, I originally added this thinking we may need to optimise our Redis writes, but it doesn't seem like we are hitting any limits so will close.
