### ISSUE TITLE
Filter duplicate duration metrics

### ISSUE THREAD

**Issue by Ishatt** [near/queryapi#208]
Description

The EXECUTION_DURATION is written only after the indexer succeeds, this means that when it is not running, or erroring, the last successful duration is exposed via the /metrics endpoint. Grafana will continue to scrape this metric giving the appearance that the given indexer is running at a constant duration.

We need to somehow filter out these duplicate metrics. Reseting the metric to 0 on error/skip doesn’t work as it will be reset almost instantly after a successful run, and because Grafana scrapes infrequently, it is likely that the actual successful metric will be missed.

**Comment by morgsmccauley** [comment]
We should use `Histogram` rather than `Gauge`
