### ISSUE TITLE
A link to a tutorial on how to build an indexer from scratch

### ISSUE THREAD

**Issue by Ishatt** [near/queryapi#225]
Description

Case-study 1: Feed Indexer

Case-study 2: Top posts by likes

Case-study 3: Ref Finance Total Transaction Volume daily

**Comment by bucanero** [comment]
We have the Feed indexer tutorial here: https://docs.near.org/bos/tutorial/indexer-tutorials/feed-indexer

We also have two other tutorials:
- https://docs.near.org/bos/tutorial/indexer-tutorials/posts-indexer
- https://docs.near.org/bos/tutorial/indexer-tutorials/hype-indexer
