### ISSUE TITLE
Describe existing QueryAPI limitations

### ISSUE THREAD

**Issue by Ishatt** [near/queryapi#227]
- Let users know that historical processing won't happen in order
- To explain out of order processing, when a start_from_block is entered there should an ‘Out of Order Processing’ toggle which can’t be switched off. Info text can say that tip of network and historical processing will happen at the same time.
Once we build the communication between real-time and historical we can change it to always off. - Gabe Hamilton

**Comment by pkudinov** [comment]
Let's add info on that in the documentation for now @bucanero
