### ISSUE TITLE
Create a Beta Registration Google Form

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#236]
- [x] Create a form
- [ ] Add link to the form into QueryAPI.App on BOS
- [ ] Add a link to https://docs.near.org/bos/queryapi/intro#known-limitations

**Comment by pkudinov** [comment]
@roshaans @bucanero , could you please complete above two items using this form link: https://forms.gle/PpmDRpGr81LhzbjC9 ?

**Comment by bucanero** [comment]
> @roshaans @bucanero , could you please complete above two items using this form link: https://forms.gle/PpmDRpGr81LhzbjC9 ?

Sure, I'm adding the link to QueryApi docs 👍

**Comment by pkudinov** [comment]
Updated the link: http://bit.ly/near-queryapi-beta
