### ISSUE TITLE
Go through obstacles that DevHub indexer developer had and list things to add to documentation

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#282]

**Comment by bucanero** [comment]
https://docs.google.com/document/d/1tMTO1GNWM11CnTkedZ_m3wbUOFlaGs7mk4T63gi1JgE/edit?usp=sharing

**Comment by bucanero** [comment]
Tickets created:
- #216 
- #303 
- #304 
- #305 
- #228 
- #306 
- #307
