### ISSUE TITLE
QueryAPI: historical processing missing block_height 102162334

### ISSUE THREAD

**Issue by eduohe** [near/queryapi#336]
QueryAPI: historical processing missing block_height 102162334

From Bo Yao:

"I encountered a potential Query API bug that a specific block processing is silently skipped in QueryAPI. The indexer is bo.near/devhub_v17 , the block in question is 102162334 . When I enable debug mode and run this block, it logs the dump has been added to database. I have a big try catch that either logs the dump has been added to database or logs Error creating xxx if this blocks runs in production.  But query in the indexer logs, neither case is logged for this block.
I think the likely cause is the historical processing for this block 102162334 is missing, failed or timed out, result in nothing (include the indexer logging itself) is written to the database. The block missing is most unlikely, since debug run does have this block. If it's failed or timed out, the bug is that Query API should have console.log logs recorded into database.
This problem blocks us from search certain devhub posts. This issue is quite deterministic to reproduce - fork the indexer gives the same result. Can someone take a look, maybe you have some server side logs that not stored in database that has the info? I'm also glad to assist debug and fix this issue!"

![missing_block](https://github.com/near/queryapi/assets/11862123/22b64861-fc56-4f10-b9d0-3fe51bcd2ad0)

From Pavel:

"Thanks Bo Yao ! 
Likely an issue in how we are indexing the blocks that include receipts for a given smart contract. 
Eduardo Ohe could you please file a bug and take a look whether this block is present in the databricks index and if not, add logic to include it"

**Comment by ailisp** [comment]
I found some clue. On bigquery, the block in question exist:
```
select * from `bigquery-public-data.crypto_near_mainnet_us.blocks` b
where
b.block_height=102162334;
```
And the receipt action that I processed in indexingLogic exist:
```
select ra.args,ra.block_height from `bigquery-public-data.crypto_near_mainnet_us.receipt_actions` ra 
where 
 ra.receipt_id='Afs2L5WdYUfGBRkvf8A6Cue6QTpmrJXiqYbcrn8aGkf9';
```

The block height is 102162333 (one block earlier). For [this receipt](https://legacy.explorer.near.org/transactions/D1HmFXbbeTPqnPgWsJcQD8LdvowNEQ3wTE5KkJuFc5Yc#Afs2L5WdYUfGBRkvf8A6Cue6QTpmrJXiqYbcrn8aGkf9), the transaction that create this receipt is executed in 102162333 and the receipt is executed in 102162334.

This is different with [a receipt action that is successfully dumped by an indexer](https://legacy.explorer.near.org/transactions/ApJcKzcLVB639okeyMPrgpwN7W1qPYR2NFpDP9eERV38#8dC3kLSh52ySf1unX54c7X69q6gQziHt8baBxRc6AWG7)

```
select ra.args,ra.block_height from `bigquery-public-data.crypto_near_mainnet_us.receipt_actions` ra 
where 
 ra.receipt_id='8dC3kLSh52ySf1unX54c7X69q6gQziHt8baBxRc6AWG7';
```
 In the successfully dumped case, the transaction that create the receipt is in 102170142, and the receipt is executed in 102170143, but above bigquery gives a block height 102170143 (The block height when receipt executes). Recall the fail to dump case, the bigquery gives the block height 102162333 (The block height when transaction executes). If indexer worker were trying to find receipt actions where block height = 102162334, it would not find the receipt.

So there maybe a off one error in storing receipt action into public dataset, but it's unclear to me why it not happens to every receipt action

**Comment by eduohe** [comment]
@pkudinov @ailisp quick update:

1) The receipt_id that @ailisp mentioned in the ticket comment `8dC3kLSh52ySf1unX54c7X69q6gQziHt8baBxRc6AWG7` is in the block_height `102170143`  on `2023-09-28` and is present in the json file databricks index:
![Screenshot 2023-10-30 at 3 03 21 PM](https://github.com/near/queryapi/assets/11862123/ad2ef6e0-e869-41db-8cd5-bf0b597f9f37)

2) 2. The logic to produce the index JSON file is the same that we use for all the other tables. silver_blocks -> silver_chunks -> silver_receipts -> silver_action_receipts -> silver_action_receipt_actions
![Screenshot 2023-10-30 at 3 05 05 PM](https://github.com/near/queryapi/assets/11862123/6ff9c9bd-e007-47ff-a7ba-96be0f34390a)

Here is the code for the pipeline that generates the data for silver_action_receipt_actions table https://github.com/near/near-databricks-lakehouse/blob/main/src/lakehouse/notebooks/Silver%20Lake%20Mainnet.sql

and here is the code for the pipeline that creates the json file:
https://github.com/near/near-databricks-lakehouse/blob/main/src/lakehouse/notebooks/QueryAPI.py

**Comment by ailisp** [comment]
Hi @eduohe Thanks for looking into this! And the logic diagram you shared is very helpful.
`8dC3kLSh52ySf1unX54c7X69q6gQziHt8baBxRc6AWG7` is a receipt that my indexingLogic can successfully found. Let's look at the missing one `Afs2L5WdYUfGBRkvf8A6Cue6QTpmrJXiqYbcrn8aGkf9`. 

So I looked at `Silver Lake Mainnet.sql`, silver_chunks -> silver_receipts -> silver_action_receipts -> silver_action_receipt_actions are simply pass chunk.block_height all the way to action receipt action. So I check whether chunk's block_height is correct:

```
select r.block_height, r.chunk_hash, r.index_in_chunk from `bigquery-public-data.crypto_near_mainnet_us.receipts` r
where
 r.receipt_id='Afs2L5WdYUfGBRkvf8A6Cue6QTpmrJXiqYbcrn8aGkf9';
```

Above shows chunk's block height is 102162333
<img width="507" alt="image" src="https://github.com/near/queryapi/assets/13259400/735d1985-b2c3-4fa0-921c-76421520734a">

but the receipt is included in block height 102162334:

The block: https://legacy.explorer.near.org/blocks/ASAaG39sY5PemvhWmoRaEbVieKYUwGLrRivqJpvfMPUf
The receipt: https://legacy.explorer.near.org/transactions/D1HmFXbbeTPqnPgWsJcQD8LdvowNEQ3wTE5KkJuFc5Yc#Afs2L5WdYUfGBRkvf8A6Cue6QTpmrJXiqYbcrn8aGkf9

And looking for the chunk that contains the receipt, either by block height or chunk hash, found no chunks:
```
select * from `bigquery-public-data.crypto_near_mainnet_us.chunks` c where c.block_height=102162333;
select c.block_height from `bigquery-public-data.crypto_near_mainnet_us.chunks` c where c.chunk_hash='FakaarN7uxYD255nrdpKpZ8u9qUAvocKacLpsnHnc2wY';
```

**Comment by ailisp** [comment]
I also made a minimal repro indexer: https://near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=bo.near/repro&view=editor-window


So this indexer logic is quite simple:
```js
async function getBlock(block: Block) {
  // Add your code here
  const h = block.header().height;
  if (h == 102162334) {
    await context.set("found", h);
    let receipt = block.actionByReceiptId(
      "Afs2L5WdYUfGBRkvf8A6Cue6QTpmrJXiqYbcrn8aGkf9"
    );
    await context.set("receipt", JSON.stringify(receipt));
  } else if (h == 102170143) {
    await context.set("found2", h);
    let receipt = block.actionByReceiptId(
      "8dC3kLSh52ySf1unX54c7X69q6gQziHt8baBxRc6AWG7"
    );
    await context.set("receipt2", JSON.stringify(receipt));
  }
  await context.set("height", h);
}
```

In debug mode, add 102162334 and 102170143 to the block list, you can see both receipt and receipt2 are set in `Setting Key/Value` log. 

But start the indexer (I set it to start from height 100000000, with contract filter = devgovgigs.near), in graphql playground,
```
query MyQuery {
  bo_near_repro_indexer_storage {
    key_name
    value
  }
}
```

Only receipt2 is set, this means indexer doesn't see block 102162334. Maybe this is a bug of contract filter?

**Comment by eduohe** [comment]
Hi @ailisp , no worries, you're most welcome.

I found the chunk `FakaarN7uxYD255nrdpKpZ8u9qUAvocKacLpsnHnc2wY` that you mentioned in the chunks table:


![Image](https://github.com/near/queryapi/assets/11862123/87b93ba6-dd15-484e-a163-4cc592449459)



![Image](https://github.com/near/queryapi/assets/11862123/2c5ebe39-2a52-4bd0-8118-37b3d511a226)

The block height of this chunk is `102162333` too. I'm not sure why legacy explorer is calculating a different block_height, but here is the explorer code:
https://github.com/near/near-indexer-for-explorer/blob/master/database/src/adapters/receipts.rs

**Comment by ailisp** [comment]
Do you have some clues on indexer debug mode and published one behaves differently? The repro is [above comment](https://github.com/near/queryapi/issues/336#issuecomment-1786444175?). Some assumption I have

- Is the indexer debug mode and published mode running on different data (S3 dump vs bigquery)?
- Or is it related to contract filter - production mode has a mandatory contract filter, while run on debug mode we can set it to run on the given block. From above repro indexer, ` if (h == 102162334) {  await context.set("found", h);` does not result in a set in published indexer, indicate block 102162334 is filtered out even before calling indexingLogic's `getBlock`

**Comment by eduohe** [comment]
I'm not sure how QueryAPI debug mode is parsing the data, maybe @roshaans or @morgsmccauley can help you with more details in this portion of the QueryAPI system.

BigQuery is just a mirror of Databricks Lakehouse that uses the near lake S3 raw files as data source, if you download the S3 json file from the block `102162333`:
https://near-lake-data-mainnet.s3.eu-central-1.amazonaws.com/000102162333/shard_3.json

 you will find the receipt `Afs2L5WdYUfGBRkvf8A6Cue6QTpmrJXiqYbcrn8aGkf9`
![Screenshot 2023-11-01 at 4 43 38 PM](https://github.com/near/queryapi/assets/11862123/7888405b-78a5-4d17-b8a1-4ecdcc52b985)

**Comment by ailisp** [comment]
I see, thank you! So there is off-one difference in how S3 data source and QueryAPI debug mode. On QueryAPI debug mode, the receipt `Afs2L5WdYUfGBRkvf8A6Cue6QTpmrJXiqYbcrn8aGkf9` can be found in block 102162334 but it's not in block 102162333.

I have a feeling that QueryAPI published mode filter contract with S3 data source (found block 102162333, filtered out 102162334), but execution logic is same as the debug mode (so it doesn't see this receipt in block 102162333), I'm trying to confirm this fact by spin out an indexer that store unique content on block 102162333 and 102162334. 

@roshaans Can you help me understand how QueryAPI's contract filter and getBlock works in backend, both debug mode and published mode?

**Comment by eduohe** [comment]
No worries @ailisp you're most welcome, I hope these infos were helpful.
I'll reassign this ticket to @roshaans so you both can continue the debug on QueryAPI

**Comment by ailisp** [comment]
I dig into the queryapi backend code, and found there is a discrepancy between QueryAPI debug mode and publish mode. 

In debug mode, blocks are fetched from aws directly by the block height: s3://near-lake-data-mainnet/000102162334/, the publicly exposed version: https://70jshyr5cb.execute-api.eu-central-1.amazonaws.com/block/102162334.

In production mode, contract filter is first applied and get a list of block height, then only run indexingLogic on this subset of blocks. For the block in problem (block height 102162334), its date is 09/28/2023, and should in this file:

s3://near-delta-lake/silver/accounts/action_receipt_actions/metadata/near/devgovgigs/2023-09-28.json

However this file doesn't contain the block, only 102162333 and some blocks after 102162334. And looking at block [102162334](https://70jshyr5cb.execute-api.eu-central-1.amazonaws.com/block/102162334), it certainly contains receipts from  So this should be a bug in the code that indexing into near-delta-lake. Do you know which repo and code are doing that?

**Comment by morgsmccauley** [comment]
I'm not sure I completely understand the problem but let me try and add some context:

@ailisp as you've discovered - we do not apply the contract filters on the UI in debug mode, so any block you specify as input will be used to execute your function. But manually selected blocks may not actually be executed on the backend if they don't satisfy the contract filter.

Regarding block `102162333` and `102162334` - I believe the current behaviour is expected:
- `102162333` is where the receipt originated
- `102162334` is where the receipt was executed, hence it's placement in `receipt_execution_outcomes`

The contract [filtering logic](https://github.com/near/queryapi/blob/396c59eaf6b93b5fbaedb227b3f34ae397dbcc57/indexer/indexer_rules_engine/src/outcomes_reducer.rs#L21) only looks at `receipt_execution_outcomes` which is why we see the latter being included over the former.

@eduohe correct me if I'm wrong - I assume this logic is the same for `near-delta-lake`, looking at the index file you linked ([devgovgigs/2023-09-28.json](https://s3.console.aws.amazon.com/s3/object/near-delta-lake?region=eu-central-1&prefix=silver/accounts/action_receipt_actions/metadata/near/devgovgigs/2023-09-28.json)), I can see block `102162334` which somewhat backs up this assumption.

I created a simple indexer pointing at `devgovgigs.near` and saw that it pulled block `102162334`, so unless I am mistaken, I don't think there is any problem with the index files or consumption of them.

@ailisp does this answer your question at all? Could you maybe try creating the indexer again? Are you expecting `102162333` or `102162334`? Please let me know if I am off the mark here.

**Comment by ailisp** [comment]
@morgsmccauley Thanks to look into this! I expect 102162334 or receipt_execution_outcomes. It was not the case ([devgovgigs/2023-09-28.json](https://s3.console.aws.amazon.com/s3/object/near-delta-lake?region=eu-central-1&prefix=silver/accounts/action_receipt_actions/metadata/near/devgovgigs/2023-09-28.json) was containing 102162333), but @eduohe has fixed it in https://github.com/near/near-databricks-lakehouse/commit/0e42f0d4862a079e89becd3f3df6e977f648f4b7, so now you look into this json file, it contains 102162334. So this issue has been fixed!
