### ISSUE TITLE
Create an NFT indexer example (adopt the NEAR Lake Framework Tutorial)

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#342]
https://docs.near.org/tutorials/indexer/nft-indexer

**Comment by bucanero** [comment]
- BOS component: https://near.org/near/widget/ComponentDetailsPage?src=bucanero.near/widget/query-api-nft-feed
- Indexer: https://near.org/#/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=bucanero.near/nft_v4&view=editor-window
