### ISSUE TITLE
Multiple contract filter doesn't work

### ISSUE THREAD

**Issue by ailisp** [near/queryapi#354]
From https://docs.near.org/bos/queryapi/index-functions#multiple-contracts-filter, it allows

> if you want to get events from every contract on the blockchain, simply define * as the filter.

 However it's not allowed on the UI:

<img width="496" alt="image" src="https://github.com/near/queryapi/assets/13259400/ab5c6dce-26c5-4b4b-9ee2-a59f37863f90">

**Comment by gabehamilton** [comment]
@bucanero @pkudinov I think we should update the docs to take out this sentence and say that it's not supported but is on the longer term roadmap. We could also include a link to the BigQuery dataset since some `*` usages will be analytical cases better suited to BigQuery.

**Comment by pkudinov** [comment]
I think we will prioritize this for this quarter
