### ISSUE TITLE
S3 `NoSuchKey` error causing historical backfill to fail

### ISSUE THREAD

**Issue by morgsmccauley** [near/queryapi#370]
Historical Backfill will read from S3 to gather blocks related to the provided contract filter. Under some conditions the process may encounter a `NoSuchKey` error, which will cause the historical process to exit, resulting in no historical messages being published.

This error needs to be investigated, and either fixed, or ignored if appropriate.

**Comment by morgsmccauley** [comment]
Blocks are often skipped in Near Protocol, I have a hunch that we are fetching all blocks within a certain range, without actually listing what is in S3, causing this `NoSuchKey` error.

If that is the case, then the work in #371, i.e. using `near-lake-framework`, should resolve this issue.

**Comment by gabehamilton** [comment]
The manual filtering handles that here https://github.com/near/queryapi/blob/main/indexer/queryapi_coordinator/src/historical_block_processing.rs#L367C52-L367C61

**Comment by morgsmccauley** [comment]
Seems to still surface somehow, example from logs:
```
Nov 07 20:32:17.714 ERROR queryapi_coordinator: Error processing historical messages: Error fetching index file 000105167047/block.json

Caused by:
    0: service error
    1: NoSuchKey: The specified key does not exist.
    2: NoSuchKey: The specified key does not exist.
```
