### ISSUE TITLE
Old indexer stop picking up new blocks when a new indexer starts

### ISSUE THREAD

**Issue by ailisp** [near/queryapi#407]
**Describe the bug**
From indexer states, old indexer stop picking up new blocks after starting a new indexer from the same account

**To Reproduce**
Query indexer state in graph ql playground:
```
      {
        "function_name": "bo.near/devhub_v32",
        "current_block_height": 105660205,
        "current_historical_block_height": 105572281
      },
      {
        "function_name": "bo.near/devhub_v33",
        "current_block_height": 105672093,
        "current_historical_block_height": 105660205
      },
      {
        "function_name": "bo.near/devhub_v34",
        "current_block_height": 105715517,
        "current_historical_block_height": 105672093
      },
      {
        "function_name": "bo.near/devhub_v35",
        "current_block_height": 105722911,
        "current_historical_block_height": 105715517
      },
      {
        "function_name": "bo.near/devhub_v36",
        "current_block_height": 105789250,
        "current_historical_block_height": 105722911
      },
```

You can see that `devhub_vN.current_block_height = devhub_v(N+1).current_historical_block_height` for all the indexers. This doesn't seem to be a coincidence. `devhub_v(N+1)` is created and started after `devhub_vN`, and at the time it provision, it has set a goal for historical processing to reach the block height at that moment. And eventually, it reaches that goal and historical processing remained same at `devhub_v(N+1).current_historical_block_height` shown above. And the older one `devhub_vN` also has stuck `current_block_height` at that block, means the new blocks since new indexer creation is not processed.

**Expected behavior**
Ideally old indexer should still picking up new indexer start. If for optimization purpose old one is stopped, then it should indicate in the dashboard, showing it as "STOPPED" (currently it shown as RUNNING). Also it would be better to let user choose to stop and delete old indexers, and maybe limit the total number of allowed indexers for system throughput.

**Comment by darunrs** [comment]
Hmm to my knowledge, one indexer doesn't impact another. I'm a bit surprised by the result of that query though. What query did you run? 

I checked both devhub_v33 and devhub_v34 and saw both on a reasonably recent block, and the same one too. I can't see any indications that one was stopped in favor of another and we don't have such a complex feature like that, as far as I can tell. There may have been some other bugs at play. Can you check again to see if your indexers are performing as expected right now?
