### ISSUE TITLE
Expose endpoint to control executors

### ISSUE THREAD

**Issue by morgsmccauley** [near/queryapi#416]
Coordinator requires a direct control point to Runner so that it can control the state of the existing Executors.

An endpoint with the following capabilities should be exposed:
- Start an Executor
- Stop an Executor
- List existing Executors

To enable a seamless transition to the Control Plane, we should be able to toggle between endpoint based control, and the existing solution in which Runner starts Executors on its own.

**Comment by darunrs** [comment]
Toggling between endpoint and existing has been moved to [this Issue](https://github.com/near/queryapi/issues/478).
