### ISSUE TITLE
Remove hardcoded shard count when constructing `StreamerMessage`

### ISSUE THREAD

**Issue by morgsmccauley** [near/queryapi#423]
We have some custom logic in Runner, and perhaps else where, which pulls the `block.json` and `shard_N.json` from NEAR Lake. For the benefit of performance, this logic assumes there are 4 shards. Soon, NEAR Protocol will expand to 5 shards. We should remove this hard coded logic and instead use the number shards specified in the Block header.

**Comment by pkudinov** [comment]
Duplicates #382
