### ISSUE TITLE
Expose endpoint to control provisioning

### ISSUE THREAD

**Issue by morgsmccauley** [near/queryapi#426]
We want to be able to control provisioning from within Coordinator. As provisioning currently exists within Runner, we should expose endpoints to control provisioning of Indexers:
- is indexer provisioned
- provision indexer

**Comment by morgsmccauley** [comment]
Having a separate endpoint will provide more control over this process - but as a first stage it may be better to just integrate this in to the executors endpoint, i.e. setting `provision: true` when starting an Executor will trigger a provisioning cycle

**Comment by pkudinov** [comment]
Duplicates https://github.com/near/queryapi/issues/759
