### ISSUE TITLE
Frontend: Show error messages regardless what editor tab user is on

### ISSUE THREAD

**Issue by roshaans** [near/queryapi#481]
At the moment, we only show error messages when the user is on the indexerFunction.js tab. Even if the user encounters a schema related error, while they are on the schema tab, they will never know or realize this. 

Instead, we should show errors on both of these tabs so the user can address them.

**Comment by jl-santana** [comment]
I addressed this on [this PR](https://github.com/near/queryapi/pull/480) Please let me know if those cover what you are referring to.

**Comment by roshaans** [comment]
We will not be doing this issue. 

@jl-santana and I discussed this point and agreed upon a few things. 

1. We should show specific error messages in the console while live editing. 
2. We should only show error messages in the browser editor when absolutely needed
     1. Publishing Indexers
     2. Switching between Schema tab -> Indexer Editor Tab.
