### ISSUE TITLE
Bug: Faulty Indexer Status

### ISSUE THREAD

**Issue by roshaans** [near/queryapi#492]
For an indexer whose real time stream execution succeeds at the latest blockheight, but it has an active historical backfill job that fails at block x, the indexer status will be faulty. 

This is because the historical backfill's failed execution will set the status of the indexer to `STOPPED`. But, when the real-time stream is active again, it will have a successful execution setting back the status to `RUNNING`. 

Expected Behavior: 
If a historical job fails, both historical and real time stream should be stopped until the error is fixed. 

Actual Behavior: 
If a historical job fails,  real time stream keeps running.

**Comment by darunrs** [comment]
Already fixed from latest changes.
