### ISSUE TITLE
Bug: Indexer Logs Reload Button Does not Reload logs

### ISSUE THREAD

**Issue by roshaans** [near/queryapi#493]
@gabehamilton reported that the indexer log page's **Reload Button** is actually not reloading the logs when pressed. Instead the page requires a reload of the full page or switch between the Editor View and Logs View. 

Possible problems: 
- logs data could be cached in browser
- Destroying and re-rendering the component does not actually trigger a new fetch request to get data

Indexer where testing was done > https://near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=dataplatform.near/components)

**Comment by darunrs** [comment]
Completed as part of https://github.com/near/queryapi/issues/573
