### ISSUE TITLE
Backfill bitmap indexer with databricks data

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#531]
Two main problems:
1. We have too much data at the same time. Either too many block heights, or too many blocks. This can crash block streamer due to memory issues.
2. Backfill can try fetching too many index files, leading to either extremely long response time, or outright failure. A guard is in place automatically error'ing if more than 1M index files are trying to be requested. 

We need a way to query matching blocks for multiple indexers or * filters quicker and with fewer S3 operations. We also need to ensure we only maintain a portion of blocks in memory at any given moment.

**Comment by pkudinov** [comment]
Next step is to try `delta-rs` for fetching index files

**Comment by darunrs** [comment]
We are now aiming for implementing and utilizing the bitmap indexer for backfills. As a result, we will focus on improving performance and stability to make the indexer viable. 

In the meantime, the indexer will be developed and run in databricks to skip a backfill process in QueryApi by dumping the database contents into the QueryApi Indexer, once deployed.

**Comment by eduohe** [comment]
I was able to translate @pkudinov  [Bitmap Javascript indexer functions code](https://near.org/dev-queryapi.dataplatform.near/widget/QueryApi.App?selectedIndexerPath=eduohe.near/bitmap_v1), to Scala UDFs, now we can use them to  write the results into the indexer PostgreSQL  table in QueryAPI as a manual backfill.  

Here is the Notebook with the Step by Step infos to use them: https://4221960800361869.9.gcp.databricks.com/?o=4221960800361869#notebook/3560207787915079/command/4231666628656698

I think it would be better to wait for the QueryAPI performance improvements before doing the backfill though

**Comment by pkudinov** [comment]
Sample code to decode bitmaps into the list of block heights: https://near.org/near/widget/ComponentDetailsPage?src=nearpavel.near/widget/QueryAPI.BitmapIndexerViewer

```
indexArrayFromCompressedBase64(a.bitmap)
        .map((idx) => a.first_block_height + idx)
```
