### ISSUE TITLE
Support from borsh-js

### ISSUE THREAD

**Issue by Tguntenaar** [near/queryapi#593]
At [Devhub](https://github.com/NEAR-DevHub) we (@ailisp and I) are currently developing an indexer for our new proposal flow. We would greatly benefit if the queryapi would support importing [borsch-js](https://github.com/near/borsh?tab=readme-ov-file#implementations) in order to easily deserialize/serialize and read structures saved on chain.

<details>
<summary>Currently, we find ourselves manually writing functions to deserialize and serialize data structures saved on-chain, as illustrated below </summary>

```js
function buildAuthorToPostIdMap(block) {
  const stateChanges = block.streamerMessage.shards
    .flatMap((e) => e.stateChanges)
    .filter(
      (stateChange) =>
        stateChange.change.accountId === "devgovgigs.near" &&
        stateChange.type === "data_update"
    );
  const addOrEditPost = stateChanges
    .map((stateChange) => stateChange.change)
    .filter((change) => base64toHex(change.keyBase64).startsWith("05"))
    .map((c) => ({
      k: Buffer.from(c.keyBase64, "base64"),
      v: Buffer.from(c.valueBase64, "base64"),
    }));
  const authorToPostId = Object.fromEntries(
    addOrEditPost.map((kv) => [
      kv.v.slice(13, 13 + kv.v.slice(9, 13).readUInt32LE()).toString("utf-8"),
      Number(kv.k.slice(1).readBigUInt64LE()),
    ])
  );
  return authorToPostId;
}
```
</details>

It would be much easier to read and index the data if a library like borsch is supported.

@morgsmccauley Please let me know if this aligns with your interests, and I'm more than willing to make a pull request myself.

**Comment by pkudinov** [comment]
Hi, @Tguntenaar this issue makes sense. I think it's worth adding a generic `fromBorsch` method and the most logical place to put it is https://github.com/near/near-lake-framework-js/tree/main/packages/near-lake-primitives so that you can
```js
import { Block, fromBorsch } from "@near-lake/primitives";
```
and use it in your code. We are more than happy to get your support on that and make it available in the indexers

**Comment by pkudinov** [comment]
The work left to be done is to publish the primitives package and deploy QueryAPI to production
