### ISSUE TITLE
Investigate Hasura Outtage Crashing Workers

### ISSUE THREAD

**Issue by darunrs** [near/queryapi#670]
Hasura occasionally experiences brief periods where mutations are not visible. This leads to any hasura actions in QueryApi failing. It's possible for this failure to occur at some inopportune time causing the worker to crash. Due to the outtage, setting of the status to STOPPED and writing of the terminating error to logs can also potentially fail. 

Investigation is necessary to find out where this error causes workers to crash, and then preventing worker crashes.

**Comment by pkudinov** [comment]
Not relevant any more
