### ISSUE TITLE
start_block is missing from certain transactions

### ISSUE THREAD

**Issue by Kevin101Zhang** [near/queryapi#673]
![Image](https://github.com/near/queryapi/assets/42101107/b1c75dc6-f6fa-45e3-9fdb-a0a2614ce772)

![Image](https://github.com/near/queryapi/assets/42101107/24099ee4-9147-430f-aec4-13ccdd5beb1c)

**Comment by pkudinov** [comment]
@darunrs can you take over this one during this sprint or we can postpone it until Kevin is back? If we can postpone, please move to the next sprint

**Comment by darunrs** [comment]
I can look into it today.

**Comment by darunrs** [comment]
Kevin already had his work up in a PR. I pulled it and verified it works. Eduardo's indexer_for_explorer indexer was consistently showing the errr and the transaction was correct when running prod frontend locally.
