### ISSUE TITLE
TimeoutError: socket hang up in Runner

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#715]
**Describe the bug**
Some indexers in DEV stop with "TimeoutError: socket hang up" error in Cloud Logs. Users see this in logs: `Encountered error processing stream: nearpavel.near/bitmap_v2:block_stream, terminating thread TimeoutError: socket hang up`

**To Reproduce**
It is hard to reproduce. Bitmap_v2 indexer keeps running for a few hours and then shuts down with this error.

**Screenshots**
![image](https://github.com/near/queryapi/assets/1334898/08ae83d6-f1b7-4aef-ac3d-302bc94c2935)
![image](https://github.com/near/queryapi/assets/1334898/5cb11e4d-a3a9-4c2e-b3cc-cff6c9b2515b)

**Comment by morgsmccauley** [comment]
I have identified the _where_ but not the _why_ - will keep this open while I continue to investigate
