### ISSUE TITLE
Landing page broken: `Indexer Function could not be found. Are you sure this indexer exists?`

### ISSUE THREAD

**Issue by mikedotexe** [near/queryapi#780]
**Describe the bug**

<img width="1770" alt="Screenshot 2024-06-07 at 6 47 33 AM" src="https://github.com/near/queryapi/assets/1042667/91905f85-5311-46d0-87a2-572906f3a46a">

**To Reproduce**

### Reproduce error

Visit NEAR docs and click on "View indexer"
https://docs.near.org/build/data-infrastructure/query-api/intro#indexers-stored-on-chain

**Expected behavior**

Page shows useful information related to blockchain indexing and does not throw an error about not being able to find an indexer.

**Additional context**
If this issue should go in another GitHub project or org, happy to move it.

**Comment by Kevin101Zhang** [comment]
https://github.com/near/docs/pull/2053
