### ISSUE TITLE
Add a READ_RPC env variable to the runner

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#796]

**Comment by morgsmccauley** [comment]
@pkudinov do you mean as in https://github.com/near/read-rpc? or any RPC endpoint?

**Comment by morgsmccauley** [comment]
@pkudinov I've added `NEAR_RPC_ENDPOINT` as `https://rpc.mainnet.near.org`, let me know if you meant read-rpc and I can change

**Comment by pkudinov** [comment]
Yeah, I meant read RPC because we need to access historical blocks

**Comment by morgsmccauley** [comment]
Ok, updated to `https://beta.rpc.mainnet.near.org`
