### ISSUE TITLE
Block lag shows incorrect values during live update

### ISSUE THREAD

**Issue by morgsmccauley** [near/queryapi#820]
The live updates to the Block Lag (`Indexer is X blocks or Y behind the blockchain tip`) incorrectly grows in value, even when the actual block lag is reducing. On fresh load, and refresh, the value appears to be correct, but it becomes incorrect after the live updates.

![image](https://github.com/near/queryapi/assets/11974624/fed7d015-736e-417d-8e1f-3adb6d2ba0a3)

**Comment by Kevin101Zhang** [comment]
props.indexerBlockHeight is static
