### ISSUE TITLE
Expose indexer query counts for dev contract

### ISSUE THREAD

**Issue by morgsmccauley** [near/queryapi#860]
We currently have the query counts for the prod contract, but also need it for dev so it can be implemented in both environments.

Dev contract: `dev-queryapi.dataplatform.near`

**Comment by eduohe** [comment]
Done ✅ 
File will be automatically updated daily :
- HTTPS: `https://storage.googleapis.com/databricks-near-query-runner/output/query-api-usage/indexers_dev.json`
- GCS: `gs://databricks-near-query-runner/output/query-api-usage/indexers_dev.json`

cc @Kevin101Zhang
