### ISSUE TITLE
Create an indexer for QueryAPI indexers

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#878]
1. Current indexer state (author, deployment date, last changed date, js code, sql code, last changed receipt, block height)
2. Indexer version history
3. For dev and prod environments

Try to use the new `block.functionCalls` method for that (https://github.com/near/near-lake-framework-js/pull/61)

Reference: https://dev.near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=kevin0.near/queryapi_indexer

**Comment by eduohe** [comment]
Prod: https://dev.near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=dataplatform.near%2Fqueryapi_indexer&transactionHashes=3TszSHH4FqW3kQFEUEuKBiTNyQZrt4SWhL9HzYSVKg2d

Dev: https://dev.near.org/dev-queryapi.dataplatform.near/widget/QueryApi.App?selectedIndexerPath=eduohe.near/queryapi_indexer

**Comment by eduohe** [comment]
cc @Kevin101Zhang
